export const API_VERSION = "v1";
export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;
export const DEFAULT_TIMEZONE = "UTC";
export const DEFAULT_CURRENCY = "USD";

export const BOOKING_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
  NO_SHOW: "NO_SHOW",
  RESCHEDULED: "RESCHEDULED",
} as const;

export const USER_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  TENANT_OWNER: "TENANT_OWNER",
  TENANT_ADMIN: "TENANT_ADMIN",
  TRAINER_LEAD: "TRAINER_LEAD",
  TRAINER: "TRAINER",
  STAFF: "STAFF",
  CLIENT: "CLIENT",
} as const;

export const ROLE_HIERARCHY: Record<string, number> = {
  SUPER_ADMIN: 100,
  TENANT_OWNER: 80,
  TENANT_ADMIN: 60,
  TRAINER_LEAD: 40,
  TRAINER: 30,
  STAFF: 20,
  CLIENT: 10,
};

export const ERROR_CODES = {
  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  // Tenant
  TENANT_NOT_FOUND: "TENANT_NOT_FOUND",
  TENANT_SUSPENDED: "TENANT_SUSPENDED",

  // Booking
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  SLOT_UNAVAILABLE: "SLOT_UNAVAILABLE",
  BOOKING_RULES_VIOLATION: "BOOKING_RULES_VIOLATION",
  BOOKING_WINDOW_EXCEEDED: "BOOKING_WINDOW_EXCEEDED",
  CANCELLATION_WINDOW_EXPIRED: "CANCELLATION_WINDOW_EXPIRED",

  // General
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
} as const;
