/**
 * Generated by scripts/generate-tokens.mjs. Do not edit by hand.
 * Source: packages/ui/src/tokens/tokens.json
 *
 * Use the CSS custom properties (tokens.css) for styling. This module exists
 * for non-CSS contexts: chart libraries, canvas, server-rendered emails,
 * tests that need the raw value, etc.
 */

export const tokens = {
  "color": {
    "light": {
      "surface": {
        "default": "#FFFFFF",
        "raised": "#FFFFFF",
        "sunken": "#F8FAFC",
        "overlay": "rgb(15 23 42 / 0.55)"
      },
      "border": {
        "subtle": "#E2E8F0",
        "default": "#CBD5E1",
        "strong": "#64748B"
      },
      "text": {
        "primary": "#0F172A",
        "secondary": "#334155",
        "muted": "#64748B",
        "inverse": "#FFFFFF",
        "onAccent": "#FFFFFF"
      },
      "accent": {
        "default": "#2E5BFF",
        "hover": "#1E40AF",
        "subtle": "#EEF2FF"
      },
      "signal": {
        "success": "#16A34A",
        "danger": "#DC2626",
        "warning": "#D97706",
        "pr": "#F59E0B"
      },
      "focusRing": "#2E5BFF"
    },
    "dark": {
      "surface": {
        "default": "#0F172A",
        "raised": "#1E293B",
        "sunken": "#020617",
        "overlay": "rgb(2 6 23 / 0.70)"
      },
      "border": {
        "subtle": "#1E293B",
        "default": "#334155",
        "strong": "#64748B"
      },
      "text": {
        "primary": "#F8FAFC",
        "secondary": "#E2E8F0",
        "muted": "#94A3B8",
        "inverse": "#0F172A",
        "onAccent": "#FFFFFF"
      },
      "accent": {
        "default": "#6366F1",
        "hover": "#818CF8",
        "subtle": "#172554"
      },
      "signal": {
        "success": "#16A34A",
        "danger": "#DC2626",
        "warning": "#D97706",
        "pr": "#F59E0B"
      },
      "focusRing": "#818CF8"
    }
  },
  "space": {
    "inset": {
      "xs": "8px",
      "sm": "12px",
      "md": "16px",
      "lg": "24px",
      "xl": "32px"
    },
    "stack": {
      "xs": "8px",
      "sm": "12px",
      "md": "16px",
      "lg": "24px",
      "xl": "40px"
    },
    "inline": {
      "xs": "4px",
      "sm": "8px",
      "md": "12px",
      "lg": "16px"
    }
  },
  "radius": {
    "control": "8px",
    "card": "12px",
    "pill": "9999px"
  },
  "duration": {
    "instant": "0ms",
    "fast": "120ms",
    "base": "200ms",
    "slow": "320ms"
  },
  "easing": {
    "standard": "cubic-bezier(0.2, 0, 0, 1)",
    "emphasized": "cubic-bezier(0.3, 0, 0, 1.2)"
  },
  "container": {
    "sm": "640px",
    "md": "768px",
    "lg": "1024px",
    "xl": "1280px",
    "2xl": "1536px"
  }
} as const;

export type Tokens = typeof tokens;
export type ThemeName = keyof Tokens["color"];
