#!/usr/bin/env node
/**
 * Reads packages/ui/src/tokens/tokens.json and emits the consumable outputs:
 *
 *   - packages/ui/src/tokens/tokens.css   (CSS custom properties, light + dark)
 *   - packages/ui/src/tokens/tokens.ts    (typed const for non-CSS contexts)
 *
 * This is the bridge between Figma Variables (the eventual source of truth)
 * and the app. Today, tokens.json is hand-authored; once the Figma export
 * pipeline is wired up (see docs/DESIGN_SYSTEM.md §4.2), only the export
 * step changes — outputs stay the same.
 *
 * Usage:
 *   node scripts/generate-tokens.mjs           # write outputs
 *   node scripts/generate-tokens.mjs --check   # fail if outputs are stale (CI)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const TOKENS_DIR = resolve(REPO_ROOT, "packages/ui/src/tokens");
const INPUT = resolve(TOKENS_DIR, "tokens.json");
const OUT_CSS = resolve(TOKENS_DIR, "tokens.css");
const OUT_TS = resolve(TOKENS_DIR, "tokens.ts");

const CHECK = process.argv.includes("--check");

const tokens = JSON.parse(readFileSync(INPUT, "utf8"));

/** Resolve `{primitive.color.brand.600}` against the tokens tree. */
function resolveRef(value, tree) {
  if (typeof value !== "string") return value;
  const match = value.match(/^\{(.+)\}$/);
  if (!match) return value;
  const segments = match[1].split(".");
  let node = tree;
  for (const seg of segments) {
    if (node == null) return value;
    node = node[seg];
  }
  return typeof node === "string" ? resolveRef(node, tree) : value;
}

function flatten(obj, prefix = []) {
  const out = [];
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;
    if (v != null && typeof v === "object") {
      out.push(...flatten(v, [...prefix, k]));
    } else {
      out.push([[...prefix, k], v]);
    }
  }
  return out;
}

function kebab(parts) {
  return parts
    .map((p) => p.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase())
    .join("-");
}

const semColorPath = (parts) => `--color-${kebab(parts)}`;

function buildThemeBlock(themeColors) {
  const lines = [];
  for (const [path, value] of flatten(themeColors)) {
    // focusRing is surfaced separately so the matching --shadow-focus
    // stays adjacent to its color.
    if (path[path.length - 1] === "focusRing") continue;
    const resolved = resolveRef(value, tokens);
    lines.push(`  ${semColorPath(path)}: ${resolved};`);
  }
  return lines.join("\n");
}

function buildRootBlock() {
  const lines = [];

  // Space
  for (const group of ["inset", "stack", "inline"]) {
    for (const [k, v] of Object.entries(tokens.semantic.space[group])) {
      lines.push(`  --space-${group}-${k}: ${resolveRef(v, tokens)};`);
    }
  }
  // Radius
  for (const [k, v] of Object.entries(tokens.semantic.radius)) {
    lines.push(`  --radius-${k}: ${resolveRef(v, tokens)};`);
  }
  // Shadow
  for (const [k, v] of Object.entries(tokens.primitive.shadow)) {
    lines.push(`  --shadow-${k}: ${v};`);
  }
  // Motion
  for (const [k, v] of Object.entries(tokens.primitive.motion.duration)) {
    lines.push(`  --duration-${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(tokens.primitive.motion.easing)) {
    lines.push(`  --easing-${k}: ${v};`);
  }
  // Font
  for (const [k, v] of Object.entries(tokens.primitive.font.family)) {
    lines.push(`  --font-${k}: ${v};`);
  }
  // Container
  for (const [k, v] of Object.entries(tokens.semantic.container)) {
    lines.push(`  --container-${k}: ${v};`);
  }
  return lines.join("\n");
}

function buildFocusRingBlock(theme) {
  const ring = resolveRef(theme.color.focusRing, tokens);
  // The translucent ring shadow uses the focus color at ~45% alpha. We keep
  // the original primitive in tokens.primitive.shadow.focus for parity, but
  // surface theme-specific overrides here.
  return [
    `  --color-focus-ring: ${ring};`,
    `  --shadow-focus: 0 0 0 3px color-mix(in srgb, ${ring} 45%, transparent);`,
  ].join("\n");
}

const css = `/*
 * Generated by scripts/generate-tokens.mjs. Do not edit by hand.
 * Source: packages/ui/src/tokens/tokens.json
 *
 * Apply via <html data-theme="light|dark">. Imported once at the app root
 * (apps/web/src/app/layout.tsx → import "@famm/ui/tokens.css").
 */

:root,
[data-theme="light"] {
${buildThemeBlock(tokens.semantic.light.color)}
${buildFocusRingBlock(tokens.semantic.light)}
}

[data-theme="dark"] {
${buildThemeBlock(tokens.semantic.dark.color)}
${buildFocusRingBlock(tokens.semantic.dark)}
}

:root {
${buildRootBlock()}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --duration-fast: 0ms;
    --duration-base: 0ms;
    --duration-slow: 0ms;
  }
}
`;

function resolveDeep(node) {
  if (typeof node === "string") return resolveRef(node, tokens);
  if (node == null || typeof node !== "object") return node;
  const out = {};
  for (const [k, v] of Object.entries(node)) out[k] = resolveDeep(v);
  return out;
}

const ts = `/**
 * Generated by scripts/generate-tokens.mjs. Do not edit by hand.
 * Source: packages/ui/src/tokens/tokens.json
 *
 * Use the CSS custom properties (tokens.css) for styling. This module exists
 * for non-CSS contexts: chart libraries, canvas, server-rendered emails,
 * tests that need the raw value, etc.
 */

export const tokens = ${JSON.stringify(
  {
    color: {
      light: resolveDeep(tokens.semantic.light.color),
      dark: resolveDeep(tokens.semantic.dark.color),
    },
    space: resolveDeep(tokens.semantic.space),
    radius: resolveDeep(tokens.semantic.radius),
    duration: tokens.primitive.motion.duration,
    easing: tokens.primitive.motion.easing,
    container: tokens.semantic.container,
  },
  null,
  2,
)} as const;

export type Tokens = typeof tokens;
export type ThemeName = keyof Tokens["color"];
`;

function readOrEmpty(p) {
  try {
    return readFileSync(p, "utf8");
  } catch {
    return "";
  }
}

if (CHECK) {
  const stale =
    readOrEmpty(OUT_CSS) !== css || readOrEmpty(OUT_TS) !== ts;
  if (stale) {
    console.error(
      "Tokens outputs are stale. Run `node scripts/generate-tokens.mjs` and commit the diff.",
    );
    process.exit(1);
  }
  console.log("Tokens outputs are up to date.");
} else {
  writeFileSync(OUT_CSS, css);
  writeFileSync(OUT_TS, ts);
  console.log("Wrote", OUT_CSS, "and", OUT_TS);
}
